"""Assemble a chaptered transcript and its knowledge checks into a video spec.

The questions are not generated by anything new here. Each chapter is presented to
the **existing** assessment pipeline as one page of a document, which buys three
things for free and without a second code path: the same no-hallucination
grounding gate, the same number of model calls as any other assessment, and —
because that pipeline already attributes every question to the page its evidence
came from — a question's `source_index` *is* its chapter index.

So the mapping from question to timeline position is not guesswork. A question is
placed at the end of the chapter whose text it was actually drawn from.
"""

from __future__ import annotations

import logging
from collections import defaultdict
from datetime import datetime, timezone

import httpx

from ..assessment.pipeline import QuestionType, generate_assessment
from ..chaptering.schema import ChapteredTranscript
from ..ingestion.schema import Block, BlockKind, Page, ParsedDocument, SourceInfo
from ..summarization.pipeline import GenerationConfig
from .schema import ChapterCheck, InteractiveVideoSpec, VideoSource

logger = logging.getLogger("ai_engine.interactive_video")


def _document_from_chapters(chaptered: ChapteredTranscript) -> ParsedDocument:
    """Present the chapters to the assessment pipeline as a document.

    This structure is an internal adapter and never leaves this module. The format
    is recorded as ``txt`` because that is what it genuinely is — the chapters'
    plain transcript text — not a claim about the original recording, whose real
    filename is carried through in ``source`` regardless.

    ``Page.index`` is deliberately the chapter's own index, so the attribution the
    assessment pipeline already performs comes back keyed by chapter.
    """
    pages = [
        Page(
            index=chapter.index,
            kind="document",
            blocks=[Block(kind=BlockKind.paragraph, text=chapter.text)],
        )
        for chapter in chaptered.chapters
        if chapter.text.strip()
    ]
    return ParsedDocument(
        source=SourceInfo(
            filename=chaptered.source.filename,
            format="txt",
            page_count=len(pages),
            title=None,
        ),
        parser="chaptering",
        parser_version=chaptered.schema_version,
        parsed_at=datetime.now(timezone.utc),
        pages=pages,
    )


async def build_interactive_video(
    client: httpx.AsyncClient,
    chaptered: ChapteredTranscript,
    video: VideoSource,
    config: GenerationConfig,
    *,
    content_id: str,
    title: str,
    question_types: list[QuestionType],
    count: int,
    language: str = "en",
) -> InteractiveVideoSpec:
    """Generate a knowledge check per chapter and compose the video specification."""
    document = _document_from_chapters(chaptered)
    assessment = await generate_assessment(
        client,
        document,
        config,
        question_types=question_types,
        count=count,
        language=language,
    )

    warnings = list(chaptered.warnings) + list(assessment.warnings)
    known = {chapter.index for chapter in chaptered.chapters}

    grouped: dict[int, list] = defaultdict(list)
    for question in assessment.questions:
        # A question whose evidence spans sections carries no attribution. Placing
        # it at an arbitrary chapter would show the learner a question about
        # something they have not reached, so it is reported instead of guessed.
        if question.source_index in known:
            grouped[question.source_index].append(question)
        else:
            warnings.append(
                f"Left {question.id} out of the interactive video: it could not be "
                "attributed to a single chapter."
            )

    checks = [
        ChapterCheck(chapter_index=index, questions=grouped[index]) for index in sorted(grouped)
    ]

    return InteractiveVideoSpec(
        content_id=content_id,
        source=chaptered.source,
        video=video,
        title=title,
        language=language,
        chapters=chaptered.chapters,
        checks=checks,
        generated_at=datetime.now(timezone.utc),
        warnings=warnings,
    )
