"""Assemble a chaptered transcript and its knowledge checks into a video spec.

The questions are not generated by anything new here. **Each chapter is presented
to the existing assessment pipeline as its own single-page document**, which buys
the no-hallucination grounding gate, the whole question-to-H5P mapping and the
warning discipline for free, without a second code path.

Why per chapter, and not one call for the whole recording: `generate_assessment`
caps questions *per type across the document it is given*. Handing it every
chapter at once therefore produces `count` questions for the entire video — the
model picks where they land, and on a long lecture that means chapter 1 gets a
check and the other twenty-three get nothing. Since the promise of this module is
a check at the end of *each* chapter, the loop over chapters belongs here, where
it is deterministic, rather than in a prompt asking a model to spread its output.

The calls are independent, so they run concurrently under a small bound: a chapter
is a short piece of text, and a rate-limited gateway would rather answer four at a
time than twenty-four. Each chapter's grounding is scoped to that chapter, which
is a stronger guarantee than document-wide grounding plus attribution: a question
on chapter 7 cannot be evidenced by chapter 2's text, because chapter 2 was never
in the prompt.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from datetime import datetime, timezone

import httpx

from ..assessment.pipeline import EmptyDocumentError, QuestionType, generate_assessment
from ..assessment.schema import AssessmentSet, Question
from ..chaptering.schema import Chapter, ChapteredTranscript
from ..ingestion.schema import Block, BlockKind, Page, ParsedDocument, SourceInfo
from ..summarization.pipeline import GenerationConfig
from .schema import ChapterCheck, InteractiveVideoSpec, VideoSource

#: How many chapters are generated for at once. Chapters are capped at 24, so this
#: bounds a single request to a handful of concurrent calls on the gateway.
_MAX_CONCURRENT_CHAPTERS = 4


@dataclass(frozen=True)
class VideoBuildOptions:
    """Everything about *this* build that is not the transcript or the gateway."""

    content_id: str
    title: str
    question_types: list[QuestionType]
    #: Questions per type, **per chapter** — see the module docstring for why that
    #: unit is enforced here rather than passed through.
    count: int
    language: str = "en"


def _document_from_chapter(chaptered: ChapteredTranscript, chapter: Chapter) -> ParsedDocument:
    """Present one chapter to the assessment pipeline as a one-page document.

    This structure is an internal adapter and never leaves this module. The format
    is recorded as ``txt`` because that is what it genuinely is — the chapter's
    plain transcript text — not a claim about the original recording, whose real
    filename is carried through in ``source`` regardless.
    """
    return ParsedDocument(
        source=SourceInfo(
            filename=chaptered.source.filename,
            format="txt",
            page_count=1,
            title=chapter.title,
        ),
        parser="chaptering",
        parser_version=chaptered.schema_version,
        parsed_at=datetime.now(timezone.utc),
        pages=[
            Page(
                index=1,
                kind="document",
                blocks=[Block(kind=BlockKind.paragraph, text=chapter.text)],
            )
        ],
    )


async def _questions_for(
    client: httpx.AsyncClient,
    chaptered: ChapteredTranscript,
    chapter: Chapter,
    config: GenerationConfig,
    options: VideoBuildOptions,
    limit: asyncio.Semaphore,
) -> tuple[list[Question], list[str]]:
    """Generate this chapter's checks, or explain why it has none.

    A chapter that produces nothing is a chapter without a knowledge check, not a
    failed request: the rest of the video is still worth packaging, so the reason
    becomes a warning and the caller sees which chapters are bare.
    """
    if not chapter.text.strip():
        return [], [f"Chapter {chapter.index} has no text, so it has no knowledge check."]
    async with limit:
        try:
            assessment: AssessmentSet = await generate_assessment(
                client,
                _document_from_chapter(chaptered, chapter),
                config,
                question_types=options.question_types,
                count=options.count,
                language=options.language,
            )
        except EmptyDocumentError:
            return [], [f"Chapter {chapter.index} has no usable text for a knowledge check."]
    warnings = [f"Chapter {chapter.index}: {warning}" for warning in assessment.warnings]
    if not assessment.questions:
        warnings.append(f"No knowledge check was generated for chapter {chapter.index}.")
    return list(assessment.questions), warnings


async def build_interactive_video(
    client: httpx.AsyncClient,
    chaptered: ChapteredTranscript,
    video: VideoSource,
    config: GenerationConfig,
    options: VideoBuildOptions,
) -> InteractiveVideoSpec:
    """Generate a knowledge check per chapter and compose the video specification."""
    limit = asyncio.Semaphore(_MAX_CONCURRENT_CHAPTERS)
    results = await asyncio.gather(
        *(
            _questions_for(client, chaptered, chapter, config, options, limit)
            for chapter in chaptered.chapters
        )
    )

    warnings = list(chaptered.warnings)
    checks: list[ChapterCheck] = []
    counter = 1
    for chapter, (questions, chapter_warnings) in zip(chaptered.chapters, results, strict=True):
        warnings.extend(chapter_warnings)
        if not questions:
            continue
        # Question ids are per-chapter out of the pipeline, so they are renumbered
        # across the video: an H5P subcontent id is derived from the id, and two
        # interactions sharing one would collide in the learner's stored state.
        renumbered: list[Question] = []
        for question in questions:
            renumbered.append(question.model_copy(update={"id": f"q{counter}"}))
            counter += 1
        checks.append(ChapterCheck(chapter_index=chapter.index, questions=renumbered))

    return InteractiveVideoSpec(
        content_id=options.content_id,
        source=chaptered.source,
        video=video,
        title=options.title,
        language=options.language,
        chapters=chaptered.chapters,
        checks=checks,
        generated_at=datetime.now(timezone.utc),
        warnings=warnings,
    )
